leftnav:
- identifier: 5e3e7c74-5a38-4d45-ad7d-78e7e1eaedb0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 035994aa-68b0-4602-8ac5-cedd472369fa
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 5eccb347-ead4-4d1e-a33f-9ae38b86c31a
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 30
- identifier: 523da9d2-dedb-480f-bf9d-ba8818f654fd
  name: 'Classes: Reading and In-class Materials'
  pageRef: /pages/classes-reading-and-in-class-materials
  weight: 40
- identifier: 8dd95eb1-f68a-4554-ab43-cb1236fc58ee
  name: Problem Sets
  pageRef: /pages/problem-sets
  weight: 50
- identifier: 198318a9-b955-4739-8f4b-05642a9bb754
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: d1616c8c-ad0b-4679-b5a8-4001eaeef45a
  name: R Studio Resources
  pageRef: /pages/studio-resources
  weight: 70
- identifier: f0be620e-b705-40cc-a9ff-7445627165e3
  name: Materials for Teachers
  pageRef: /pages/materials-for-teachers
  weight: 80
- identifier: f60559c7-2ea5-4d17-b451-0b061e172526
  name: 'R: Information, Tutorials, and Sample Code'
  pageRef: /pages/r-and-rstudio
  weight: 90
- identifier: e93fe0a3-f6d0-4eed-b8c1-8b350fafebf8
  name: Mathlets Applets
  pageRef: /pages/mathlets-applets
  weight: 100
- identifier: 900449c2-8b2d-4acb-856a-b7131a7b9d90
  name: Why Teach Probability and Statistics Together?
  pageRef: /pages/why-teach-probability-and-statistics-together
  parent: 5eccb347-ead4-4d1e-a33f-9ae38b86c31a
  weight: 10
- identifier: 4fef87b5-fe29-4ba2-9ee0-cec7c1aa24f7
  name: A Shift to Active Learning
  pageRef: /pages/a-shift-to-active-learning
  parent: 5eccb347-ead4-4d1e-a33f-9ae38b86c31a
  weight: 20
- identifier: 1a7fa00b-6a0e-4c68-abd9-9059c913fd66
  name: Learning and Teaching with R
  pageRef: /pages/learning-and-teaching-with-r
  parent: 5eccb347-ead4-4d1e-a33f-9ae38b86c31a
  weight: 30
- identifier: b4d4c351-f8bb-460d-95d8-bc763d36e728
  name: Using the Applets
  pageRef: /pages/using-the-applets
  parent: 5eccb347-ead4-4d1e-a33f-9ae38b86c31a
  weight: 40
- identifier: 9e7117e3-365d-4e16-b172-780cb4a99191
  name: Including Materials for Teachers
  pageRef: /pages/including-materials-for-teachers
  parent: 5eccb347-ead4-4d1e-a33f-9ae38b86c31a
  weight: 50
- identifier: ad455e5d-07cd-408f-bfd2-cf7c26500738
  name: 'R Tutorial A: Basics   '
  pageRef: /pages/r-tutorial-a-basics
  parent: f60559c7-2ea5-4d17-b451-0b061e172526
  weight: 10
- identifier: caf11256-bc50-4551-95a6-70ae98b5918a
  name: 'R Tutorial B: Random Numbers '
  pageRef: /pages/r-tutorial-b-random-numbers
  parent: f60559c7-2ea5-4d17-b451-0b061e172526
  weight: 20
- identifier: 0b200191-a15a-4922-912e-d8713eafef15
  name: 'R Tutorial: Functions'
  pageRef: /pages/r-tutorial-functions
  parent: f60559c7-2ea5-4d17-b451-0b061e172526
  weight: 30
- identifier: 8321e26a-a623-43e0-963c-0e5faf60910e
  name: 'R Tutorial: for Loops'
  pageRef: /pages/r-tutorial-for-loops
  parent: f60559c7-2ea5-4d17-b451-0b061e172526
  weight: 40
- identifier: 7594f920-afd2-4521-a251-bfaaf5ba3747
  name: 'R Tutorial: Run Length Encoding'
  pageRef: /pages/r-tutorial-run-length-encoding
  parent: f60559c7-2ea5-4d17-b451-0b061e172526
  weight: 50
